# Generated by Django 5.2.11 on 2026-04-12 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Require user to change password on next login.'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('username', models.CharField(help_text='Username at time of action (preserved if user deleted)', max_length=150)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('deploy', 'Deploy Service'), ('deploy_confirm', 'Confirm Deploy'), ('deploy_rollback', 'Rollback Deploy'), ('deploy_delete', 'Delete Service Deploy'), ('service_create', 'Create Service'), ('device_create', 'Create Device'), ('device_update', 'Update Device'), ('device_delete', 'Delete Device'), ('user_create', 'Create User'), ('password_change', 'Password Change'), ('health_check', 'Health Check'), ('config_view', 'View Config'), ('other', 'Other')], db_index=True, max_length=30)),
                ('detail', models.TextField(blank=True, help_text='Human-readable description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('target_object', models.CharField(blank=True, help_text="e.g. 'VPLSService:42', 'Device:3'", max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'action'], name='accounts_au_timesta_ace11a_idx'), models.Index(fields=['username'], name='accounts_au_usernam_c06607_idx')],
            },
        ),
    ]
