# Generated by Django 5.2.11 on 2026-04-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vplsservice',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('deployed', 'Deployed'), ('pending_confirm', 'Pending Confirmation'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='planned', max_length=20),
        ),
    ]
