# Generated by Django 5.2.11 on 2026-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(help_text='IP address or FQDN', max_length=255)),
                ('port', models.IntegerField(default=830)),
                ('username', models.CharField(max_length=100)),
                ('encrypted_password', models.BinaryField()),
                ('platform', models.CharField(default='SR-7750', max_length=50)),
                ('sw_version', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
