# Generated by Django 5.2.11 on 2026-04-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Health score 0-100 (100 = healthy)')),
                ('critical_count', models.IntegerField(default=0)),
                ('major_count', models.IntegerField(default=0)),
                ('minor_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Health Score',
                'ordering': ['-checked_at'],
            },
        ),
    ]
